/**
 * Created by xuanmiao on 2017/9/24.
 */
var fileStructureData = [
    {
        "id":0,
        "route":"0",
        "title":"null",
        "type":"null",
        "child":[
            {
                "id":0,
                "route":"0_0",
                "title":"最近",
                "type":"ren",
                "parent":"null",
                "child":[]
            }
        ]
    },
    {
        "id":1,
        "route":"1",
        "title":"文件",
        "child":[
            {
                "id":0,
                "route":"1_0",
                "title":"全部",
                "type":"all",
                "parent":"文件",
                "child":[
                    {
                        "id":0,
                        "route":"1_0_0",
                        "title":"软件",
                        "type":"folder",
                        "parent":"全部",
                        "child":[
                            {
                                "id":0,
                                "route":"1_0_0_0",
                                "title":"软件儿子",
                                "type":"folder",
                                "parent":"软件",
                                "child":[
                                    {
                                        "id":0,
                                        "route":"1_0_0_0_0",
                                        "title":"软件孙子",
                                        "type":"folder",
                                        "parent":"软件儿子",
                                        "child":[
                                            {
                                                "id":0,
                                                "route":"1_0_0_0_0_0",
                                                "title":"软件曾孙",
                                                "type":"folder",
                                                "parent":"软件孙子",
                                                "child":[
                                                    {
                                                        "id":0,
                                                        "route":"1_0_0_0_0_0_0",
                                                        "title":"软件玄孙",
                                                        "type":"folder",
                                                        "parent":"软件曾孙",
                                                        "child":[
                                                            {
                                                                "id":0,
                                                                "route":"1_0_0_0_0_0_0_0",
                                                                "title":"看来你很无聊",
                                                                "type":"folder",
                                                                "parent":"软件玄孙",
                                                                "child":[]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "id":1,
                        "route":"1_0_1",
                        "title":"专业知识学习",
                        "type":"folder",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":2,
                        "route":"1_0_2",
                        "title":"QQ音乐",
                        "type":"folder",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":3,
                        "route":"1_0_3",
                        "title":"群共享文件",
                        "type":"folder",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":4,
                        "route":"1_0_4",
                        "title":"QQ邮箱",
                        "type":"folder",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":5,
                        "route":"1_0_5",
                        "title":"QQ网盘",
                        "type":"folder",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":6,
                        "route":"1_0_6",
                        "title":"zd423",
                        "type":"website",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":7,
                        "route":"1_0_7",
                        "title":"word",
                        "type":"word",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":8,
                        "route":"1_0_8",
                        "title":"excel",
                        "type":"excel",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":9,
                        "route":"1_0_9",
                        "title":"ppt",
                        "type":"ppt",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":10,
                        "route":"1_0_10",
                        "title":"pdf",
                        "type":"pdf",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":11,
                        "route":"1_0_11",
                        "title":"奔跑的奶酪",
                        "type":"website",
                        "parent":"全部",
                        "child":[]
                    },
                    {
                        "id":12,
                        "route":"1_0_12",
                        "title":"阿里巴巴矢量图标库",
                        "type":"website",
                        "parent":"全部",
                        "child":[]
                    }
                ]
            },
            {
                "id":1,
                "route":"1_1",
                "title":"文档",
                "type":"doc",
                "parent":"文件",
                "child":[
                    {
                        "id":0,
                        "route":"1_1_0",
                        "title":"word",
                        "type":"word",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":1,
                        "route":"1_1_1",
                        "title":"excel",
                        "type":"excel",
                        "parent":"文档",
                        "child":[]
                    },
                    {
                        "id":2,
                        "route":"1_1_2",
                        "title":"ppt",
                        "type":"ppt",
                        "parent":"文档",
                        "child":[]
                    }
                ]
            },
            {
                "id":2,
                "route":"1_2",
                "title":"图片",
                "type":"pic",
                "parent":"文件",
                "child":[
                    {
                        "id":0,
                        "route":"1_2_0",
                        "title":"图片",
                        "type":"pic",
                        "parent":"图片",
                        "child":[]
                    }
                ]
            },
            {
                "id":3,
                "route":"1_3",
                "title":"视频",
                "type":"video",
                "parent":"文件",
                "child":[
                    {
                        "id":0,
                        "route":"1_3_0",
                        "title":"视频",
                        "type":"video",
                        "parent":"视频",
                        "child":[

                        ]
                    }
                ]
            },
            {
                "id":4,
                "route":"1_4",
                "title":"笔记",
                "type":"note",
                "parent":"文件",
                "child":[

                ]
            },
            {
                "id":5,
                "route":"0_5",
                "title":"音乐",
                "type":"music",
                "parent":"文件",
                "child":[

                ]
            }
        ]
    },
    {
        "id":2,
        "route":"2",
        "title":"照片",
        "child":[
            {
                "id":0,
                "route":"2_0",
                "title":"时间",
                "type":"time",
                "parent":"照片",
                "child":[

                ]
            }
        ]
    },
    {
        "id":3,
        "route":"3",
        "title":"我的",
        "child":[
            {
                "id":0,
                "route":"3_0",
                "title":"保险箱",
                "type":"add-safebox",
                "parent":"我的",
                "child":[

                ]
            },
            {
                "id":1,
                "route":"3_1",
                "title":"分享链接",
                "type":"share",
                "parent":"我的",
                "child":[

                ]
            },
            {
                "id":2,
                "route":"3_2",
                "title":"回收站",
                "type":"trash",
                "parent":"我的",
                "child":[

                ]
            }
        ]
    }

];